apiVersion: v1
kind: Service
metadata:
  name: macos-service
spec:
  type: LoadBalancer
  selector:
    app: macos-simulator
  ports:
  - name: vnc
    port: 5999
    targetPort: 5999
  - name: ssh
    port: 10022
    targetPort: 10022
  - name: appium
    port: 4723
    targetPort: 4723
