apiVersion: v1
kind: Service
metadata:
  name: job-server-service
spec:
  selector:
    app: job-server
  type: NodePort   # Change here for external access in minikube
  ports:
    - protocol: TCP
      port: 3000        # The port your service listens on
      targetPort: 3000  # The port your pod/container listens on
      # Optional: specify nodePort if you want a fixed port outside the cluster
      # nodePort: 30000
