# Generated by Django 5.0.9 on 2025-10-03 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=255)),
                ('app_version_id', models.CharField(db_index=True, max_length=255)),
                ('test_path', models.TextField()),
                ('priority', models.IntegerField(db_index=True, default=1)),
                ('target', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('emulator', 'Emulator')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('agent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'target'], name='jobs_job_status_7c31d3_idx'), models.Index(fields=['app_version_id', 'priority'], name='jobs_job_app_ver_782f0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('emulator', 'Emulator')], db_index=True, max_length=20)),
                ('busy', models.BooleanField(db_index=True, default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_agent', to='jobs.job')),
            ],
            options={
                'ordering': ['agent_id'],
            },
        ),
    ]
